export const footerListId = [
  "Tanya Jawab",
  "Pusat Bantuan",
  "Akun",
  "Pusat Media",
  "Hubungan Investor",
  "Lowongan Kerja",
  "Tukar Kartu Hadiah",
  "Beli Kartu Hadiah",
  "Cara Menonton",
  "Ketentuan Penggunaan",
  "Privasi",
  "Preferensi Cookie",
  "Informasi Perusahaan",
  "Hubungi Kami",
  "Uji Kecepatan",
  "Informasi Legal",
  "Hanya di Netflix",
];
export const footerListEn = [
  "FAQ",
  "Help Center",
  "Account",
  "Media Center",
  "Investor Relations",
  "Jobs",
  "Redeem Gift Cards",
  "Buy GIft Cardss",
  "Ways to Watch",
  "Terms o Use",
  "Privacy",
  "Cookie Preferences",
  "Corporate Information",
  "Contact Us",
  "Speed Test",
  "Legal Notices",
  "Only on Netflix",
];
