export const footerList = [
  "Tanya Jawab",
  "Pusat Bantuan",
  "Akun",
  "Pusat Media",
  "Hubungan Investor",
  "Lowongan Kerja",
  "Tukar Kartu Hadiah",
  "Beli Kartu Hadiah",
  "Cara Menonton",
  "Ketentuan Penggunaan",
  "Privasi",
  "Preferensi Cookie",
  "Informasi Perusahaan",
  "Hubungi Kami",
  "Uji Kecepatan",
  "Informasi Legal",
  "Hanya di Netflix",
];
